export const events = [
  {
    event: "transaction_updated",
    tags: ["Transaction", "CountTransaction", "CountCheck", "CountVoucher"],
  },
  {
    event: "transaction_created",
    tags: ["Transaction", "CountTransaction", "CountCheck", "CountVoucher"],
  },
  {
    event: "transaction_received",
    tags: ["Transaction", "CountTransaction", "CountCheck", "CountVoucher"],
  },
  {
    event: "transaction_archived",
    tags: ["Transaction", "CountTransaction", "CountCheck", "CountVoucher"],
  },
  {
    event: "transaction_approval",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
    ],
  },
  {
    event: "transaction_approved",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
    ],
  },
  {
    event: "transaction_returned",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
    ],
  },
  {
    event: "transaction_for_void",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
    ],
  },
  {
    event: "transaction_voided",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
    ],
  },
  {
    event: "cutoff_updated",
    tags: ["CutOFF", "CutOFFLogs"],
  },
  {
    event: "cutoff_created",
    tags: ["CutOFF", "CutOFFLogs"],
  },
  {
    event: "cutoff_approved",
    tags: ["CutOFF", "CutOFFLogs"],
  },
  {
    event: "schedule_created",
    tags: ["SchedTransact"],
  },

  {
    event: "schedule_updated",
    tags: ["SchedTransact"],
  },
  {
    event: "schedule_received",
    tags: ["SchedTransact"],
  },
  {
    event: "schedule_approval",
    tags: ["SchedTransact"],
  },
  {
    event: "schedule_returned",
    tags: ["SchedTransact"],
  },
  {
    event: "schedule_approved",
    tags: ["SchedTransact"],
  },
  {
    event: "schedule_generate",
    tags: [
      "SchedTransact",
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
    ],
  },
];
