export const events = [
  {
    event: "company_updated",
    tags: ["Company"],
  },
  {
    event: "department_updated",
    tags: ["Department"],
  },
  {
    event: "location_updated",
    tags: ["Location"],
  },
  {
    event: "ap_tagging_updated",
    tags: ["AP"],
  },
  {
    event: "supplier_updated",
    tags: ["Supplier", "Transaction"],
  },
  {
    event: "vat_updated",
    tags: ["VAT"],
  },
  {
    event: "atc_updated",
    tags: ["ATC"],
  },
  {
    event: "supplier_type_updated",
    tags: ["SupplierType"],
  },
  {
    event: "document_type_updated",
    tags: ["DocumentType"],
  },
  {
    event: "account_number_updated",
    tags: ["AccountNumber"],
  },
  {
    event: "account_title_updated",
    tags: [
      "GGPAccountTitles",
      "GPAccountTitles",
      "PAccountTitles",
      "CAccountTitles",
      "GAccountTitles",
      "AccountTitles",
    ],
  },
  {
    event: "transaction_updated",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "TagYear",
    ],
  },
  {
    event: "transaction_created",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "TagYear",
    ],
  },
  {
    event: "transaction_received",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "TagYear",
    ],
  },
  {
    event: "transaction_archived",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "TagYear",
    ],
  },
  {
    event: "transaction_approval",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
      "TagYear",
    ],
  },
  {
    event: "transaction_approved",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
      "TagYear",
    ],
  },
  {
    event: "transaction_returned",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
      "TagYear",
    ],
  },
  {
    event: "transaction_for_void",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
      "TagYear",
    ],
  },
  {
    event: "transaction_voided",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
      "TagYear",
    ],
  },
  {
    event: "cutoff_updated",
    tags: ["CutOFF", "CutOFFLogs"],
  },
  {
    event: "cutoff_created",
    tags: ["CutOFF", "CutOFFLogs"],
  },
  {
    event: "cutoff_approved",
    tags: ["CutOFF", "CutOFFLogs"],
  },
  {
    event: "schedule_created",
    tags: ["SchedTransact", "CountSchedule", "ScheduleLogs"],
  },

  {
    event: "schedule_updated",
    tags: ["SchedTransact", "CountSchedule", "ScheduleLogs"],
  },
  {
    event: "schedule_received",
    tags: ["SchedTransact", "CountSchedule", "ScheduleLogs"],
  },
  {
    event: "schedule_approval",
    tags: ["SchedTransact", "CountSchedule", "ScheduleLogs"],
  },
  {
    event: "schedule_returned",
    tags: ["SchedTransact", "CountSchedule", "ScheduleLogs"],
  },
  {
    event: "schedule_approved",
    tags: ["SchedTransact", "CountSchedule", "ScheduleLogs"],
  },
  {
    event: "schedule_generate",
    tags: [
      "SchedTransact",
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
      "CountSchedule",
      "ScheduleLogs",
    ],
  },
  {
    event: "transaction_read",
    tags: ["Transaction", "CountTransaction", "CountCheck", "CountVoucher"],
  },
];
