export const events = [
  {
    event: "transaction_updated",
    tags: ["Transaction", "CountTransaction", "CountCheck", "CountVoucher"],
  },
  {
    event: "transaction_created",
    tags: ["Transaction", "CountTransaction", "CountCheck", "CountVoucher"],
  },
  {
    event: "transaction_received",
    tags: ["Transaction", "CountTransaction", "CountCheck", "CountVoucher"],
  },
  {
    event: "transaction_archived",
    tags: ["Transaction", "CountTransaction", "CountCheck", "CountVoucher"],
  },
  {
    event: "transaction_approval",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
    ],
  },
  {
    event: "transaction_approved",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
    ],
  },
  {
    event: "transaction_returned",
    tags: [
      "Transaction",
      "CountTransaction",
      "CountCheck",
      "CountVoucher",
      "Logs",
      "AccountTitles",
      "GTAG",
      "VPCheckNumber",
      "VPJournalNumber",
      "SingleCheck",
      "SingleJournal",
      "CheckEntries",
      "JournalEntries",
    ],
  },
];
